import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import Link from "next/link";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <style jsx>
        {`
          h3 {
            margin-bottom: 30px;
            font-size: 25px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          {/* <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p> */}
          {/* <div>
            <a
              href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              target='_blank'
              rel='noopener noreferrer'
            >
              By{" "}
              <Image
                src='/vercel.svg'
                alt='Vercel Logo'
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}
        </div>

        <h1>Hunting Coder</h1>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src='/logo.png'
            alt='Next.js Logo'
            width={150}
            height={150}
            priority
          />
        </div>
        <div>
          <h3>A blog for hunting coders by hunting coder</h3>
          <div className='blogs'>
            <h2>Popular Blogs</h2>
            <div className={styles.blogItem}>
              <h3>How to learn React in 2023...</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn React in 2023...</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn React in 2023...</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
            <div className={styles.blogItem}>
              <h3>How to learn React in 2023...</h3>
              <p>Javascript is the language used to design logic for the web</p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
